# Text for the v10 sheet update. Run: python3 v10_sheet_text.py  -> writes formula_*.txt files
import json

def q(s):
    s = s.replace('"', "'")
    parts = s.split("\n\n")
    return '&CHAR(10)&CHAR(10)&'.join('"%s"' % p for p in parts) if len(parts) > 1 else '"%s"' % s

def arr(rows):
    return "={" + ";".join(",".join(q(c) if isinstance(c, str) else str(c) for c in r) for r in rows) + "}"

# Projects rows 14-22, columns E..O:
# E Status, F One-line, G Description, H Facility, I Key numbers, J Timeline, K Team, L Partners, M Funding, N Link, O Image link
P = [
 ["Active",
  "Near-infrared multi-object spectroscopy of H II galaxies at z = 1.5–2.5 with EMIR on the 10.4-m GTC, extending the L(Hβ)–σ relation as a cosmic distance indicator.",
  "H II galaxies are compact, gas-rich starbursts (EW(Hβ) ≳ 50 Å, R_eff ≲ 1 kpc) whose Hβ luminosity scales steeply with the velocity dispersion of the ionized gas, L(Hβ) ∝ σ⁵. That makes them standardizable candles that can bridge the distance-indicator desert at z ≈ 1.5–3, beyond the reach of Type Ia supernovae. The team observed H II galaxies with EMIR (near-infrared multi-object spectroscopy) and MEGARA on the GTC as part of the GOYA guaranteed-time survey between 2013 and 2019.\n\nThe limiting factor is the intrinsic scatter of the relation, up to ~0.3 dex in the local Universe. Current work uses the resolved kinematics from MEGARA to correct for non-Gaussian line profiles and second parameters — the same correction that reduces the scatter for local luminous compact blue galaxies from 0.65 to 0.37 dex — so that a corrected L–σ calibration is ready for application at z ≈ 1.5–3. Part of this is run as a SEASTAR student research project with Chulalongkorn University.",
  "10.4-m GTC / EMIR and MEGARA", "z = 1.5–2.5; L(Hβ) ∝ σ⁵; GOYA survey, 30 guaranteed nights", "GTC programs 2013–2019; calibration work ongoing",
  "Krittapas Chanchaiworawit", "R. Guzmán (University of Florida); GOYA survey team; Chulalongkorn University (SEASTAR student project)", "", "https://research.iac.es/proyecto/emir/pages/general-description/science-goya-east.php",
  "emir_footprint.jpg (hero: SHOC 571 Euclid VIS/Y/J image with the MEGARA footprint and Hα contours — SEA OtTeRS / NARIT; imaging ESA/Euclid)"],
 ["Active",
  "Sérsic-profile decomposition of ~16,000 SDSS AGN hosts as a predictor of supermassive black-hole growth (Klipbua, Chanchaiworawit & Sarajedini, APRIM 2026).",
  "Does the shape of a galaxy tell us how its black hole grew? This project fits three-component models — an AGN point source plus inner and outer Sérsic profiles — to the SDSS images of about 16,000 low-luminosity Seyfert-1 AGN at z = 0–0.9 with black-hole masses of 10⁶–10⁹ solar masses, drawn from the sample of Chanchaiworawit & Sarajedini (2024). Black-hole masses come from multicomponent spectral decomposition; simulations set the reliability limits (S/N > 40, AGN fraction < 0.8, fitting error < 0.5 dex), and coefficients are bootstrapped in the g', r', and i' bands.\n\nFirst results, presented by Thatchayuth Klipbua at APRIM 2026 in Hong Kong: the Sérsic index correlates positively with black-hole mass and with Eddington ratio, and negatively with redshift — hosts at higher redshift are less morphologically developed.",
  "SDSS imaging and spectra", "~16,000 Seyfert-1 AGN; z = 0–0.9; log M_BH = 6–9; 3-component Sérsic fits", "Talk at APRIM 2026 (Hong Kong, May 5, 2026)",
  "Thatchayuth Klipbua; Krittapas Chanchaiworawit", "V. Sarajedini (Florida Atlantic University)", "", "https://aprim2026.org/",
  "agnm_n_mbh.jpg (hero: Sérsic index vs black-hole mass by redshift bin) + agnm_model, agnm_heat — T. Klipbua / SEA OtTeRS, APRIM 2026 talk"],
 ["",
  "Systematic identification of protoclusters at cosmic noon, led by Atthaporn Pramoun.",
  "A new line of work that extends the team's protocluster census from z = 6.5 and the JADES fields toward cosmic noon, when today's clusters were assembling. It builds on the density-contrast mapping already developed for JADES GOODS-N and GOODS-S (number density within R = 5 cMpc, scaled by the galaxy bias to a matter-density contrast, with cores of most-massive-progenitor scale) and applies it systematically to identify protocluster candidates. Method paper and first catalog in preparation.",
  "JWST and HST archives", "", "Started 2026",
  "Atthaporn Pramoun; Krittapas Chanchaiworawit", "", "", "",
  "jwst_map.jpg (hero, reused: GOODS-N/S density-contrast maps — Chanchaiworawit et al., in prep)"],
 ["Active",
  "Integral-field study of star formation, the spin parameter, and local matter density in galaxies with MEGARA/GTC, MaNGA/SDSS, and Hector/AAT.",
  "Why does star formation in the early Universe come in short, sharp bursts, and why do galaxies quench as they fall into clusters? The team's working hypothesis is spin-regulated star formation: gas with high angular momentum keeps a galaxy's spin parameter high and its fuel spread out; when the high-spin gas is removed — by ram-pressure stripping, harassment, strangulation, or mergers on the way into a dense environment — the rest funnels to the center and fuels a burst, after which the galaxy runs dry. Protocluster cores at z ≈ 2–4, with shallow potential wells and no hot intracluster medium yet, should therefore be bursty; assembled low-redshift clusters should be quenched; and the HI-rich field should show a clean spin–gas-mass relation.\n\nThe test is done in the nearby Universe, where spin, HI mass, and radial velocities can be measured directly: new MEGARA observations at the GTC (R = 5,000–20,000 in the optical) of galaxies selected by size, HI mass, and star-formation rate, alongside archival MaNGA and SAMI cubes, and Hector on the AAT. Twenty-six local luminous compact blue galaxies are already in hand. The first batch shows high specific star-formation rates in slow-rotating open-field H II galaxies from the GTC filler programs; more targets across HI fractions and environments are being added.",
  "10.4-m GTC / MEGARA; SDSS MaNGA; SAMI; AAT / Hector", "MEGARA R = 5,000–20,000; 26 local LCBGs in hand", "Observations and analysis ongoing (2025–)",
  "Krittapas Chanchaiworawit; Narenrit Thananusak", "", "", "",
  "ifu_targets.jpg (hero: SDSS cutouts of MEGARA targets with IFU position angles — SDSS imaging; overlay SEA OtTeRS) + ifu_kin, ifu_select, jwst_journey, manga (SDSS/MaNGA, CC BY: Dana Berry / SkyWorks Digital, David Law, SDSS)"],
 ["Completed",
  "Diamond-turned slit-viewing mirrors and slit masks for DARTS, the robotic transient spectrograph NARIT is building for Lick Observatory.",
  "DARTS (Dual-beam Automatic Rapid Transient Spectrograph) is a fully robotic low-resolution spectrograph for classifying transients — supernovae, variable stars, active galaxies — in the era of large surveys such as the Vera C. Rubin Observatory. It covers 360–1,000 nm simultaneously in blue and red channels at R ≈ 1,000, with a K-mirror image derotator and an EMCCD slit-viewing camera. The optical design comes from UCO/Lick; most of the mechanical design, manufacturing, assembly, and alignment happens at NARIT. The first unit is bound for the Left Nasmyth port of the 2.4-m Automated Planet Finder at Lick Observatory, California, with a second planned for the Thai National Telescope.\n\nSEAL Lab's contribution is the reflective optics: the slit-viewing mirrors were the first prototype on the lab's list in February 2024, were machined on the Freeform L and verified on the DynaFiz interferometer, and are now mounted on the DARTS bench. The slit masks are also cut by single-point diamond turning. Delivered as a FY2568 output.",
  "5-axis SPDT machine; DynaFiz interferometer", "DARTS: 360–1,000 nm dual channel; R ≈ 1,000; slit-viewing mirror aperture ≈ 90 mm", "Prototype list Feb 2024; mirrors delivered FY2568 (2025)",
  "Tarathon Intaros; Picha Ruenarrom; Krittapas Chanchaiworawit", "UCO / Lick Observatory; NARIT DARTS team (Samaporn Tinyanont, Thansita Thomrungpiyathan)", "NARIT program ST68", "https://www.narit.or.th/en/technology-development/advanced-optics/DARTS",
  "darts_mirror.jpg (hero: slit-viewing mirror on the DARTS bench with its DynaFiz form map — SEAL Lab / NARIT) + darts_kmirror_lab, darts_kmirror_cad, darts_render (NARIT)"],
 ["Active",
  "Can we 3D-print a mirror? Diamond turning and testing of additively manufactured aluminum mirror substrates for space missions, with the UK Astronomy Technology Centre.",
  "Additive manufacturing lets a mirror be printed with a lightweight lattice behind its face — attractive for CubeSats and space telescopes — but only if the printed alloy can be diamond-turned to an optical finish. The team machined six substrates under identical conditions (2,000 rpm, 5 mm/min feed, 2 µm depth of cut, 21–23 °C): a cast RSA 6061 baseline, AlSi10Mg from two suppliers, and Scalmalloy, each with and without hot isostatic pressing (HIP). Stress-relieved AlSi10Mg reached a surface roughness Sq of 2.99–3.77 nm, close to the cast baseline of 2.23 nm, while HIP closed pores but coarsened the grains and roughly doubled the roughness (7.67 nm for AlSi10Mg + HIP, 12.53 nm for Scalmalloy + HIP). Specular reflectance over 400–900 nm matched cast aluminum for Scalmalloy and reached 70–80% for AlSi10Mg. The conclusion: printed mirror substrates are viable today with the right alloy and heat treatment.\n\nThe work grew out of the Newton Fund STFC–NARIT project on freeform-optics manufacturing (Durham University lead, 2020–2022) and a 2022 SPIE study of lightweight mirror design for conventional and additive manufacturing. It was published at SPIE Astronomical Telescopes + Instrumentation 2026 (Ruenarrom et al.) and continues with AM mirror prototypes for the ADOT 6U CubeSat with UK ATC. A PMU-B FY2570 proposal (F11) would take a CubeSat micro space-telescope prototype built from freeform 3D-printed parts and SPDT mirrors through a full space-qualification chain (outgassing, atomic oxygen, thermal vacuum, vibration, radiation) with TINT, UK ATC, and RAL Space, from TRL 3 to 4–5.",
  "5-axis SPDT machine; ZeGage profilometer; DynaFiz interferometer", "Sq: cast 2.23 nm; AlSi10Mg (SR) 2.99–3.77 nm; Scalmalloy (SR) 7.57 nm; + HIP 7.67–12.53 nm", "Newton Fund 2020–2022; SPIE 2022 and 2026; PMU-B F11 proposal Aug 2026",
  "Picha Ruenarrom; Tarathon Intaros; Krittapas Chanchaiworawit; Manlika Pinkaew", "UK Astronomy Technology Centre (C. Atkins, Y. Chahid, V. Oyarzun, S. McPhee, L. Millan); Durham University (CfAI); RAL Space; TINT", "Newton Fund STFC–NARIT (2020–2022); NARIT program ST68–ST70; PMU-B FY2570 F11 (proposed)", "https://doi.org/10.1117/12.3104367",
  "am_substrates.jpg (hero: six substrates before and after SPDT — SEAL Lab / NARIT) + am_lattice (lattice structure by UK ATC), am_micro, am_ral (NARIT team at RAL Space, Feb 2025)"],
 ["Active",
  "Primary and secondary mirrors, machined in-house by diamond turning, for the Thai Space Consortium's 3U and 6U CubeSat space telescopes.",
  "NARIT's CubeSat program is developing two Cassegrain space telescopes whose mirrors are made in Thailand for the first time: a 3U unit (about 6 kg, 100 × 100 × 340.5 mm, 4.7 m ground sampling distance from a 550-km sun-synchronous orbit) and a 6U unit (about 12 kg, 100 × 200 × 340.5 mm, 1.8 m ground sampling distance). SEAL Lab machines the M1 and M2 mirrors from GD&T-controlled shop drawings on the Freeform L, verifies their form on the DynaFiz interferometer, and aligns the optics in the lab; the 3U mirror is built on a lightweight lattice back.\n\nThe lab also delivered the retroreflectors for TSC-1 and a prototype tertiary mirror for TSC-1's hyperspectral imager among its FY2568 outputs, and the 6U optics were shown to the leadership of the Ministry of Higher Education, Science, Research and Innovation during its visit to the lab. The satellites are assembled in Thailand with a ground station at NARIT.",
  "5-axis SPDT machine; DynaFiz interferometer; SEAL Lab alignment bench", "6U: ~12 kg, 100 × 200 × 340.5 mm, 1.8 m GSD at 550 km; 3U: ~6 kg, 4.7 m GSD; 3U mirror Ø ≈ 52 mm", "Prototypes FY2568–FY2569 (2025–2026)",
  "Tarathon Intaros; Picha Ruenarrom; Krittapas Chanchaiworawit", "Thai Space Consortium (TSC)", "NARIT program ST68–ST70", "https://www.narit.or.th/th/technology-development/space-system-technologies/CubeSat-3U-6U",
  "tsc_align.jpg (hero: MHESI leadership viewing the 6U CubeSat optics under alignment at SEAL Lab — NARIT) + tsc_layout, tsc_6u_mirrors, tsc_3u_mirror (SEAL Lab / NARIT), tsc_cubesat (NARIT)"],
 ["Planned",
  "Proposed upgrade of the diamond-turning line to 700 mm and to low-expansion glass (Zerodur, ULE, fused silica), with Oxford's HARMONI team and ESO, aimed at ELT-class freeform optics.",
  "HARMONI is the first-light visible and near-infrared integral-field spectrograph of ESO's Extremely Large Telescope, led by the University of Oxford and now in its final design phase. Its optics — and those of other ELT instruments — call for large freeform mirrors in low-thermal-expansion glass. SEAL Lab's Freeform L currently handles workpieces up to 650 mm in metal. The N43 Frontier Research Infrastructure proposal submitted to PMU-B in August 2026 would raise the capacity to 700 mm, qualify ductile-regime machining of fused silica, ULE, and Zerodur, add a sub-micron defect-inspection microscope and coating and vacuum equipment, and produce at least three ELT-class demonstration optics with Ra ≤ 5 nm and PV ≤ 0.1 µm, reviewed and accepted by the Oxford HARMONI team and ESO. The plan takes the brittle-optics production line from TRL 4 to 6 in twelve months, trains six certified engineers, and targets entry into the ELT instrument supply chain.\n\nStatus: proposal under evaluation. Oxford and ESO have committed in-kind contributions (optical-design effort, interface specifications, instrument requirements, and facility access) matching NARIT's request.",
  "5-axis SPDT machine (upgrade to Ø 700 mm proposed); DynaFiz interferometer", "Ø 700 mm; Ra ≤ 5 nm; PV ≤ 0.1 µm; TRL 4 → 6; 12 months", "Proposal submitted Aug 2026 (PMU-B FY2570, N43)",
  "Krittapas Chanchaiworawit; Tarathon Intaros; Picha Ruenarrom", "University of Oxford (HARMONI instrument team); ESO", "PMU-B FY2570 N43 (proposed, ≥ 20 M THB with 50% partner co-investment)", "https://harmoni-elt.physics.ox.ac.uk/",
  "harmoni_eso.jpg (hero: artist's impression of the HARMONI model — credit ESO, CC BY 4.0) + spdt_machine2 (NARIT's Freeform L — SEAL Lab / NARIT)"],
 ["",
  "Tertiary mirror for a radio telescope.",
  "Scope, telescope, and schedule to be confirmed by the team.",
  "", "", "", "", "", "", "", ""],
]
open("formula_projects_v10.txt", "w").write(arr(P))

# Existing project descriptions (single cells)
G4 = "Commissioned on the 0.7-m Thai Robotic Telescope at NARIT AstroPark, with first light on Jan 27, 2025. CoLoRS covers 400–700 nm at R ≈ 100–200 in a 15.2-kg package with no moving parts; a dichroic at 805 nm sends the red light to the guider, so the same unit guides and takes spectra. It reaches S/N > 100 at r' ≈ 12 in under a minute and had logged nine nights on the TRT by March 2026. The optomechanical design, on-sky performance, upgraded mechanical components, and robotic control software were published at SPIE 2025 and 2026.\n\nNext steps: science verification on the 0.8-m telescope at Phitsanulok in early 2027, and CoLoRS-NEX, which adds a C-RED 2 InGaAs short-wave-infrared imager (zyJH bands). The exposure-time calculator is developed by Plan Nitiwarangkul."
G8 = "The LRS is the workhorse long-slit spectrograph for the 2.4-m Thai National Telescope: 400–800 nm with a 960 l/mm VPH grism, interchangeable slits of 4.5″, 2.7″, and 1.8″ giving R ≈ 300, 500, and 750, and an Andor Newton BEX2-DD CCD held at −100 °C by a thermoelectric cooler and a Thorlabs LK220 chiller. In its latest on-sky tests it reached r' = 20.8 AB at S/N 5 in one hour (21.5 in two hours). The prototype installed in December 2018 delivered R ≈ 800–1,300 over 440–740 nm (Paenoi et al. 2019).\n\nThe instrument was offered to the community as a shared-risk mode in Cycle 13 (December 2025 – May 2026) and enters full operations in Cycle 14 (October 2026 – May 2027). A user-friendly GUI and packaged reduction routines are in development; the guiding-camera mount, detector cooling, and upgraded mechanical components are described in Tharawan et al. (SPIE 2026), and the autoguiding and robotization software in Chomchuen et al. (SPIE 2026)."
G6 = "NARIT's simulation-software development for ARRAKIHS began in 2018, and the institute is represented in the mission consortium by the team PI. NARIT's CHALAWAN cluster is one of four computing systems supporting mission simulations worldwide: the mock observations feed the mission's image-simulation pipeline and also yield cosmological dN/dz science from the background galaxies.\n\nThe mission was adopted by ESA's Science Programme Committee on 10–11 June 2026 as the second F-class mission (F2), with launch planned for late 2030. ARRAKIHS will image the faint outskirts of at least 80 Milky-Way-mass galaxies over 3–5 years with two binocular telescopes covering 280–1,600 nm in four bands, to count stellar streams and satellites and so test the nature of dark matter. The consortium spans nearly 48 institutions in 17 countries; Thailand is a contributing country through NARIT."
open("formula_cells_v10.json", "w").write(json.dumps({"G4": G4, "G8": G8, "G6": G6,
  "K6": "Krittapas Chanchaiworawit; Wissarut Jarernsupapon; Narenrit Thananusak; Utane Sawangwit",
  "N6": "https://www.narit.or.th/en/ResearchNews-20260612-NARIT-ARRAKIHS",
  "O4": "colors_night.jpg (hero) + colors_night2, colors_design, colors_cad — SEA OtTeRS / NARIT (SPIE 2026 deck, commissioning poster)",
  "O8": "lrs_tnt.jpg (hero) + lrs_box, lrs_open, lrs_model, lrs_raytrace, lrs_cooling — SEA OtTeRS / NARIT",
  "O5": "spdt_action.jpg (hero) + spdt_action, dynafiz, coating, mirrors, substrates, cleanroom, seal_interior, seal_team, zegage — SEAL Lab / NARIT",
  "O6": "arrakihs.jpg (hero: simulated galaxy halo, A. Camazón / ARRAKIHS consortium, CC BY 4.0) + arrakihs_bino (Satlantis / AMC), arrakihs_narit (NARIT news graphic, 12 Jun 2026), arrakihs_assembly (NARIT news; Satlantis / AMC)",
}, ensure_ascii=False, indent=1))

# People: That (row 9) B..K ; Kantapong new row 12 A..Y ; misc cells
THAT = ["BSc (MSc student)", "SEA OtTeRS", "Research Assistant", "Research assistant · instrument-control and observing software",
  "National Astronomical Research Institute of Thailand (Public Organization) / Chiang Mai University", "",
  "Develops the control, autoguiding, and reduction software for the LRS and CoLoRS spectrographs, from camera control to plate solving.",
  "That Chomchuen is a Research Assistant at NARIT (since March 2025), developing software for astronomical photometry and spectroscopy: Python- and .NET-based control of CCD and CMOS cameras, plate-solving and star-tracking, and the observing software for the team's instruments. He holds a BSc in Statistics (first-class honors, 2021) from Chiang Mai University, where he is now an MSc student in Computer Science.\n\nHe is first author of the SPIE 2026 paper on the unified software architecture for real-time autoguiding and robotization of the LRS and CoLoRS spectrographs at the TRT and TNT.",
  "Instrument-control software; CCD and CMOS camera control; plate solving and star tracking; image processing and machine learning; autoguiding and robotization of spectrographs",
  "Software engineer · LRS and CoLoRS control, autoguiding, and robotization"]
open("formula_that_v10.txt", "w").write(arr([THAT]))
KANT = ["Kantapong Tharawan", "BEng", "SEA OtTeRS", "Mechanical Engineer", "Mechanical engineer · Center for Optics and Photonics",
  "National Astronomical Research Institute of Thailand (Public Organization)", "",
  "Mechanical engineer behind the LRS and CoLoRS hardware: guider mounts, detector cooling, telescope adaptors, and the DARTS truss.",
  "Kantapong Tharawan is a Mechanical Engineer at NARIT's Center for Optics and Photonics (since 2025). He designed the guiding-camera mount and the detector cooling for the LRS, the CoLoRS adaptor for the PlaneWave CDK700 with its counterweight and computer structure, alignment equipment for the 2.4-m Thai National Telescope, and the truss for the DARTS spectrograph, and he supports the K-mirror alignment. He graduated in Mechanical Engineering from Chiang Mai University in 2024.\n\nHe is first author of the SPIE 2026 paper on the upgraded mechanical components for the LRS and CoLoRS.",
  "Opto-mechanical design; finite-element analysis (ANSYS); SolidWorks; detector cooling and mounts; telescope interfaces",
  "Mechanical engineer · LRS and CoLoRS mechanical components, DARTS truss",
  "https://drive.google.com/file/d/1WRP4QAxi0A8PsXpnsLpdA1J0xr6x85Uv/view", "https://drive.google.com/file/d/1rWTmUQxi-xOmeaF_RwbGXuVUw2FnJqij/view",
  "", "", "", "", "", "", "", 2025, "", "", "", "Yes"]
open("formula_kantapong_v10.txt", "w").write(arr([KANT]))
print("ok", len(P), len(THAT), len(KANT))
